### ISSUE TITLE
Diffs from maskrcnn-benchmark? 

### ISSUE THREAD

**Issue by kamatsuoka** [naoto0804/fast-line-drawing-vectorization#2]
Thanks for your interesting work. Would it be possible to publish your diffs from maskrcnn-benchmark so that we can see where you customized their algorithm and network parameters?

**Comment by naoto0804** [comment]
The difference is in postprocessing of mask-RCNN predictions specific for line drawing parsing (e.g., remove predictions on white-pixels).
For more details, please refer to the already published [paper](https://drive.google.com/open?id=1KC8HaReRsIZ4V8wdAjZ2U4WKxIhewIFW).

**Comment by kamatsuoka** [comment]
Thanks Naoto. As for the detailed masks,

> We extract 256 x Н / 16 x W /16 features by RoiAlign. In the mask branch, the features are gradually up-sampled, as shown in Table I. We finally get much finer 1 x Н / 2 x W/2
masks for each Rol.

is that configured in the config files, such as https://github.com/naoto0804/fast-line-drawing-vectorization/blob/master/configs/kanji_m32_b32_pool8.yaml ?

**Comment by naoto0804** [comment]
Exactly.
